- name: "configure {{component}}"
  become: yes 
  # hosts: "{{component}}" # for ansible
  hosts: localhost # for terraform
  connection: local  # for terraform
  roles: # this will automatically load a folder called roles in current working directory
  - "{{component}}"